// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhotoFolder.Infrastructure.Data;

namespace PhotoFolder.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("PhotoFolder.Core.Domain.Entities.FileLocation", b =>
                {
                    b.Property<string>("RelativeFilename")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("Hash");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("RelativeFilename");

                    b.HasIndex("Hash");

                    b.ToTable("FileLocation");
                });

            modelBuilder.Entity("PhotoFolder.Core.Domain.Entities.FileOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.Property<string>("SourceFilename");

                    b.Property<string>("SourceHash");

                    b.Property<string>("TargetFilename");

                    b.Property<string>("TargetHash");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("FileOperations");
                });

            modelBuilder.Entity("PhotoFolder.Core.Domain.Entities.IndexedFile", b =>
                {
                    b.Property<string>("Hash")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<DateTimeOffset>("FileCreatedOn");

                    b.Property<long>("Length");

                    b.Property<DateTimeOffset>("ModifiedOn");

                    b.HasKey("Hash");

                    b.ToTable("IndexedFiles");
                });

            modelBuilder.Entity("PhotoFolder.Core.Domain.Entities.FileLocation", b =>
                {
                    b.HasOne("PhotoFolder.Core.Domain.Entities.IndexedFile")
                        .WithMany("Files")
                        .HasForeignKey("Hash");
                });

            modelBuilder.Entity("PhotoFolder.Core.Domain.Entities.IndexedFile", b =>
                {
                    b.OwnsOne("PhotoFolder.Core.Domain.PhotoProperties", "PhotoProperties", b1 =>
                        {
                            b1.Property<string>("IndexedFileHash");

                            b1.Property<string>("BitmapHash")
                                .IsRequired()
                                .HasColumnName("PhotoBitmapHash");

                            b1.Property<int>("Height")
                                .HasColumnName("PhotoHeight");

                            b1.Property<int>("Width")
                                .HasColumnName("PhotoWidth");

                            b1.HasKey("IndexedFileHash");

                            b1.ToTable("IndexedFiles");

                            b1.HasOne("PhotoFolder.Core.Domain.Entities.IndexedFile")
                                .WithOne("PhotoProperties")
                                .HasForeignKey("PhotoFolder.Core.Domain.PhotoProperties", "IndexedFileHash")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
